server:
  port: 8080

spring:
  application:
    name: ecommerce-service
  datasource:
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

shardingsphere:
  datasource:
    names: ds0
    ds0:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC
      username: root
      password: password
  rules:
    sharding:
      tables:
        t_order:
          actual-data-nodes: ds0.t_order_$->{0..1}
          table-strategy:
            standard:
              sharding-column: user_id
              sharding-algorithm-name: order-inline
      sharding-algorithms:
        order-inline:
          type: INLINE
          props:
            algorithm-expression: t_order_$->{user_id % 2}

grpc:
  server:
    port: 9090
